[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
inventory = "0.3.20"
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
